version: "3.9"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      # db initialization script
      - ./migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - ./migrations/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      - POSTGRES_DB=todo-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  service:
    build: ./server/.
    environment:
      # server must wait for DB to be up
      WAIT_HOSTS: db:5432
      WAIT_TIMEOUT: 60
    volumes:
      - ./server/:/code/
    ports:
      - "9000:9000"
    depends_on:
      - db
  client:
    build: ./client/.
    command: npm start
    volumes:
      - ./client/:/code/
    ports:
      - "3000:3000"
    depends_on:
      - service
